apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dvwa-sample
  namespace: default
spec:
  selector:
    matchLabels:
      app: dvwa-sample-app
  replicas: 1
  template:
    metadata:
      labels:
        app: dvwa-sample-app
    spec:
      containers:
      - name: dvwa-sample
        image: vulnerables/web-dvwa
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 500m
            memory: 200Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-sample-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dvwa-sample-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dvwa-sample-ingress
  namespace: default
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect : "false"
spec:
  rules:
  - host: teddy-kub-test.dev.daumkakao.io
    http:
      paths:
      - path: /
        backend:
          serviceName: dvwa-sample-svc
          servicePort: 80
