version: '3'

services:

  mdb:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sokobanpass
    ports:
      - 3306:3306
    volumes:
      - /Users/sokoban/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
